name: "Rust CI"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    uses: darbiadev/.github/.github/workflows/rust-lint.yaml@1163b50ed46a8aea41806ee86ec2eb50605521ac

  clippy:
    needs: lint
    uses: darbiadev/.github/.github/workflows/rust-clippy.yaml@1163b50ed46a8aea41806ee86ec2eb50605521ac

  test:
    needs: clippy
    strategy:
      matrix:
        triple:
          - {
            os: "ubuntu-latest",
            target: "x86_64-unknown-linux-gnu",
          }
          - {
            os: "macOS-latest",
            target: "x86_64-apple-darwin",
          }
          - {
            os: "windows-latest",
            target: "x86_64-pc-windows-msvc",
          }

    uses: darbiadev/.github/.github/workflows/rust-test.yaml@1163b50ed46a8aea41806ee86ec2eb50605521ac
    with:
      os: ${{ matrix.triple.os }}
      target: ${{ matrix.triple.target }}
