name: "Rust CI"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    uses: darbiadev/.github/.github/workflows/rust-lint.yaml@c6e8cd8568c3872c86bc65ec43483343b3c98480

  clippy:
    needs: lint
    uses: darbiadev/.github/.github/workflows/rust-clippy.yaml@c6e8cd8568c3872c86bc65ec43483343b3c98480

  test:
    needs: clippy
    strategy:
      matrix:
        triple:
          - {
            os: "ubuntu-latest",
            target: "x86_64-unknown-linux-gnu",
          }
          - {
            os: "macOS-latest",
            target: "x86_64-apple-darwin",
          }
          - {
            os: "windows-latest",
            target: "x86_64-pc-windows-msvc",
          }

    uses: darbiadev/.github/.github/workflows/rust-test.yaml@c6e8cd8568c3872c86bc65ec43483343b3c98480
    with:
      os: ${{ matrix.triple.os }}
      target: ${{ matrix.triple.target }}
